"""
Targeted repack & extract script for routes missing route_source.pt / route_features.pt.

Reads missing_routes.txt (generated by debug_dataset_paths.py), then runs
Phase 1 (pack_source) + Phase 2 (extract) ONLY on those routes.

Usage:
    python scripts/repack_missing_routes.py \
        --dataset_path /path/to/pdm_lite \
        --config_path  /path/to/all_towns \
        --model_path   /path/to/model_0030_1.pth \
        --device       cuda:0 \
        --batch_size   16
"""

import os
import sys
import argparse
from pathlib import Path

# Ensure project root is importable
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from model.transfuser_extractor.preprocess_dataset import DatasetPreprocessor


def main():
    parser = argparse.ArgumentParser(description="Repack & extract only missing routes")
    parser.add_argument('--dataset_path', type=str, required=True)
    parser.add_argument('--config_path', type=str, required=True)
    parser.add_argument('--model_path', type=str, default=None)
    parser.add_argument('--device', type=str, default='cuda:0')
    parser.add_argument('--batch_size', type=int, default=16)
    parser.add_argument('--missing_list', type=str, default=None,
                        help='Path to missing_routes.txt (default: scripts/missing_routes.txt)')
    args = parser.parse_args()

    # Locate missing_routes.txt
    if args.missing_list:
        missing_list_path = args.missing_list
    else:
        missing_list_path = os.path.join(os.path.dirname(__file__), 'missing_routes.txt')

    if not os.path.exists(missing_list_path):
        print(f"ERROR: {missing_list_path} not found.")
        print("Run  python scripts/debug_dataset_paths.py  first to generate it.")
        sys.exit(1)

    # Read missing routes
    with open(missing_list_path) as f:
        lines = [l.strip() for l in f if l.strip()]

    missing_routes = []
    for line in lines:
        # Format: "EventName/RouteName"
        route_dir = Path(args.dataset_path) / line
        if route_dir.is_dir():
            missing_routes.append(route_dir)
        else:
            print(f"  WARNING: route dir does not exist on disk: {route_dir}")

    if not missing_routes:
        print("No missing routes to process. All good!")
        return

    print(f"\n{'='*60}")
    print(f"  Reprocessing {len(missing_routes)} missing routes")
    print(f"{'='*60}")
    for r in missing_routes:
        print(f"  - {r.parent.name}/{r.name}")

    # Initialize preprocessor
    preprocessor = DatasetPreprocessor(
        dataset_path=args.dataset_path,
        config_path=args.config_path,
        model_path=args.model_path,
        device=args.device,
        batch_size=args.batch_size,
        skip_existing=False,  # Force re-process
    )

    # Phase 1: pack_source for each missing route
    print(f"\n[Phase 1] Packing source data for {len(missing_routes)} routes ...")
    from tqdm import tqdm
    packed_count = 0
    for route_dir in tqdm(missing_routes, desc="Packing source"):
        try:
            preprocessor.pack_source_route(route_dir)
            source_pt = route_dir / 'route_source.pt'
            if source_pt.exists():
                packed_count += 1
            else:
                print(f"  WARNING: pack_source_route ran but route_source.pt still missing: {route_dir.name}")
                # Diagnose
                lidar_dir = route_dir / 'lidar'
                rgb_dir = route_dir / 'rgb'
                n_laz = len(list(lidar_dir.glob('*.laz'))) if lidar_dir.exists() else 0
                n_jpg = len(list(rgb_dir.glob('*.jpg'))) if rgb_dir.exists() else 0
                print(f"           lidar/ has {n_laz} .laz files, rgb/ has {n_jpg} .jpg files")
        except Exception as e:
            print(f"  ERROR packing {route_dir.name}: {e}")
    print(f"Phase 1 done: {packed_count}/{len(missing_routes)} routes packed successfully.")

    # Phase 2: extract features
    print(f"\n[Phase 2] Extracting features for {len(missing_routes)} routes ...")
    import torch
    extracted_count = 0
    for route_dir in tqdm(missing_routes, desc="Extracting features"):
        source_pt = route_dir / 'route_source.pt'
        try:
            if source_pt.exists():
                source_pack = torch.load(source_pt, weights_only=True)
            else:
                source_pack = None  # fallback to per-frame IO
            preprocessor.process_route(route_dir, source_pack=source_pack)
            feat_pt = route_dir / preprocessor.feature_dir_name / 'route_features.pt'
            if feat_pt.exists():
                extracted_count += 1
            else:
                print(f"  WARNING: process_route ran but route_features.pt still missing: {route_dir.name}")
        except Exception as e:
            print(f"  ERROR extracting {route_dir.name}: {e}")
    print(f"Phase 2 done: {extracted_count}/{len(missing_routes)} routes extracted successfully.")

    # Summary
    print(f"\n{'='*60}")
    print(f"  Summary")
    print(f"{'='*60}")
    print(f"  Total missing routes: {len(missing_routes)}")
    print(f"  Packed (route_source.pt):   {packed_count}")
    print(f"  Extracted (route_features.pt): {extracted_count}")
    still_missing = len(missing_routes) - extracted_count
    if still_missing > 0:
        print(f"\n  WARNING: {still_missing} routes still missing features!")
        print(f"  Check the route directories for corrupted/incomplete source data.")
    else:
        print(f"\n  All routes successfully processed!")


if __name__ == '__main__':
    main()
